### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by winding-lines** [maidsafe/safe_crypto#6]
There are 3 licenses referenced in the library
- MIT/BSD in the readme
- GPL in lib.rs

Could you please clarify in which direction you want to go?

Many thanks!

**Comment by nbaksalyar** [comment]
The `lib.rs` license was incorrect, it should be MIT/BSD.
This is [fixed now](https://github.com/maidsafe/safe_crypto/blob/13d1740df50c3feb3dd93e531331baab13745aa1/src/lib.rs#L3-L5).
Thank you!
